name: iPadTaskManager
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: zh-Hans

targets:
  iPadTaskManager:
    type: application
    platform: iOS
    sources:
      - path: iPadTaskManager
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: iPadTaskManager/Info.plist
        CODE_SIGN_ENTITLEMENTS: iPadTaskManager/iPadTaskManager.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.example.iPadTaskManager
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 2
        SUPPORTS_MACCATALYST: NO
        INFOPLIST_KEY_CFBundleDisplayName: "任务管理"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.education"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        SWIFT_VERSION: "5.0"
    dependencies:
      - framework: FamilyControls.framework
        embed: false
      - framework: DeviceActivity.framework
        embed: false
      - framework: ManagedSettings.framework
        embed: false

  iPadTaskManagerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: iPadTaskManagerTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: iPadTaskManager
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/iPadTaskManager.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/iPadTaskManager"

  iPadTaskManagerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: iPadTaskManagerUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: iPadTaskManager
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: iPadTaskManager
